default:
   uri: /

all:
   new_sessions, same_session

new_sessions:
   empty, welcome

same_session:
    rezept, myknzlpzl, show, cat, cat5, letter

empty:
    uri: /empty/index
    new_session: true

welcome:
    uri: /welcome/index
    new_session: true

rezept:
    uri: /rezept/index

myknzlpzl:
    uri: /rezept/myknzlpzl

show:
    uri: /rezept/show/713

cat:
    uri: /rezept/cat/Hauptspeise

cat5:
    uri: /rezept/cat/Hauptspeise?page=5

letter:
    uri: /rezept/letter/G

links:
  - 
    uri: /test/url_test
  -
    uri: /test/link_test

alpha:
    uri: /rezept/alphabetic

test_index:
    uri: /test/index
